### ISSUE TITLE
Can't retrieve a specific Region

### ISSUE THREAD

**Issue by yoshizzle** [linode/linode_api4-python#113]
I can do this to retrieve all Regions:

_from linode import LinodeClient_

_client = LinodeClient(token)

_client.get_regions()_

But I can't retrieve an individual region because I cannot filter on id or label.

**Comment by lwm** [comment]
You can also use the https://github.com/linode/linode_api4-python/issues/139#issue-361865222 code sample trick to get all unique groups.
