### ISSUE TITLE
How to access a list of Invoice Items?

### ISSUE THREAD

**Issue by yoshizzle** [linode/linode_api4-python#115]
I do not see a way to retrieve a list of invoice line items.

**Comment by fenhl** [comment]
I've tried adding this functionality myself but invoice items seem to be in an unusual spot as far as the API goes where there is no endpoint for an individual item. Is there any other API resource like that so I can look at how it's implemented here?

**Comment by yoshizzle** [comment]
@fenhl - sorry for the confusion. You can access that endpoint from our docs:

https://developers.linode.com/api/v4/

Search for "List Invoice Items" for specific information. The endpoint is: _GET /account/invoices/{invoiceId}/items_

Hope this helps.

**Comment by Dorthu** [comment]
These actually were not accessible in the python client - I have a fix coming up in a minute
