### ISSUE TITLE
linode.instance_create() function doesn't generate a proper password sometimes

### ISSUE THREAD

**Issue by HarikrishnanEA** [linode/linode_api4-python#129]
I've run into this issue where calling this function (with parameters fro region, image and group alone) doesn't create a password for with the appropriate length, and raises ApiError.

The system I was running on is a linode instance itself and gives sys.version_info[0] as 2.

**Comment by Dorthu** [comment]
Thanks for reporting this, I'll look into it

**Comment by Dorthu** [comment]
Do you happen to have an example password that was generated but was not valid, or maybe the error that was returned from the API?  I'm having trouble reproducing this issue.

**Comment by HarikrishnanEA** [comment]
I wasn't able to log the password created then, but this was the part of the code that was run:

```
new_linode, password = self.client.linode.instance_create(ltype=self.config.plan,
                                                    region = chosen_region,
                                                    image = self.config.image_id,
                                                    group = self.config.group)

```
And the following error was produced:
```
  File "/root/linode-daemon/utils.py", line 157, in create_li
    group = self.config.group)
  File "/root/proxyenv/local/lib/python2.7/site-packages/linode_api4/linode_client.py", line 258, in instance_create
    result = self.client.post('/linode/instances', data=params)
  File "/root/proxyenv/local/lib/python2.7/site-packages/linode_api4/linode_client.py", line 868, in post
    return self._api_call(*args, method=requests.post, **kwargs)
  File "/root/proxyenv/local/lib/python2.7/site-packages/linode_api4/linode_client.py", line 839, in _api_call
    raise ApiError(error_msg, status=response.status_code, json=j)
linode_api4.errors.ApiError: 400: Password must be between 6 and 128 characters; 

```

**Comment by Dorthu** [comment]
Thanks for the additional details - I just pushed a fix, I'll have a new build out in a few minutes.  When you have a chance and you upgrade and confirm that this is fixed?

**Comment by HarikrishnanEA** [comment]
Sorry, I'm not in a position to be able to test this myself. I am using the API as part of a project for someone else and don't want them to be billed for additional linode instances created.

I think the code changes made should do the trick though.

**Comment by Dorthu** [comment]
That's cool, thanks for taking the time to report this and follow up.  I'm going to close this issue, but if the issue persists don't hesitate to reopen it.
