### ISSUE TITLE
instance_create TypeError: Instance object is not iterable

### ISSUE THREAD

**Issue by bengland2** [linode/linode_api4-python#131]
In the comments for the [instance_create method here](https://github.com/linode/linode_api4-python/blob/master/linode_api4/linode_client.py#L179), it says that you can create a linode passing just the type and region.   This is so that you can specify non-default configuration for the linode before you boot it.  For example, I'd like to reconfigure the disks.  However, this does not work:

```
(Pdb) new_linode, 
password = api4_client.linode.instance_create(vmtype, region)
2018-08-07 18:17:12,564 DEBUG Starting new HTTPS connection (1): api.linode.com:443
2018-08-07 18:17:14,173 DEBUG https://api.linode.com:443 "POST /v4/linode/instances HTTP/1.1" 200 573
*** TypeError: 'Instance' object is not iterable
```
However, if I specify the image with:

```
(Pdb) new_linode, password = api4_client.linode.instance_create(vmtype, region,booted=False, image=selected_image)
2018-08-07 18:25:24,504 DEBUG Starting new HTTPS connection (1): api.linode.com:443
2018-08-07 18:25:26,268 DEBUG https://api.linode.com:443 "POST /v4/linode/instances HTTP/1.1" 200 586
```
 It succeeds.  The problem with this is that it creates a 650-GB system disk with centos on it, but what I want is a 25-GB system disk and want to free up the remaining space to create another raw disk that I can use for my application.  The reason for this is that the IOPS on these disks is so high compared to volumes ([linode ticket here](https://manager.linode.com/support/ticket/10769242))

```
(Pdb) new_linode.disks[0].size
2018-08-07 18:27:38,248 DEBUG Starting new HTTPS connection (1): api.linode.com:443
2018-08-07 18:27:38,519 DEBUG https://api.linode.com:443 "GET /v4/linode/instances/9477899/disks HTTP/1.1" 200 394
654848
(Pdb) new_linode.disks[1].size
2018-08-07 18:27:43,270 DEBUG Starting new HTTPS connection (1): api.linode.com:443
2018-08-07 18:27:43,596 DEBUG https://api.linode.com:443 "GET /v4/linode/instances/9477899/disks HTTP/1.1" 200 394
512
```

Is there any way I can do what I want to do  with this API, and if so can you provide some sample code or documentation that illustrates how?    If not, is there any way I can get a volume with the same IOPS?  Patrick Donnelly has code that used the older linode API to do this.  [Here is his code](https://github.com/batrick/ceph-linode/blob/master/linode-launch.py#L82).

Thanks very much for whatever assistance you can provide - Ben England, Red Hat Perf. Engr.

**Comment by Dorthu** [comment]
The `instance_create` method only returns a tuple if you call it with an `image`, if you just specify a `type` and `region` it will return the new Linode instance only (see [the docs for instance_create](https://linode-api4.readthedocs.io/en/latest/linode_api4/linode_client.html#linode_api4.linode_client.LinodeGroup.instance_create), this is the last section titled "Create an empty instance").  It would look something like this:

```
instance = client.linode.instance_create("g6-standard-2", "us-east")
```
Once your empty instance is created, you may need to add a delay before provisioning disks - the API doesn't allow operation on a busy Linode instance. This library makes doing so easy:

```
while instance.status == "provisioning":
    time.sleep(1)
```

This will poll the API for updated status and exit the loop when it changes (not all attributes poll, only volatile ones do).  

I'm on my phone right now, but I'll add a more complete code sample tomorrow morning.  I hope this helps in the interim.
