### ISSUE TITLE
Top level linode group method

### ISSUE THREAD

**Issue by lwm** [linode/linode_api4-python#139]
I'm building an Ansible dynamic inventory source for Linode and want to retrieve unique group names.

So far, I am doing this:

```python
        self.linode_groups = set(
            filter(None, (
                instance.group
                for instance
                in self.client.linode.instances())
            )
        )
```

It would be nice to have something high level like `self.client.linode.groups()`.

Would this be possible?

**Comment by Dorthu** [comment]
Not with the way the API is designed right now, unfortunately.  Linode groups are deprecated and unlikely to get any support in the future to make this practical.  However, this is another way - we recently shipped a "tags" feature that works a lot like groups, but allows multiple tags per Linode (among other things).  I'm working on a PR to introduce tags to this library right now, should have it up by EOD - this will work the way you want:

```python
self.tags = [t.label for t in self.client.tags()]
```

The Linode object will also have a mutable "tags" property (a list of strings) that associates them to tags.  [The docs](https://developers.linode.com/api/v4#tag/Tags) have more info, and I'll include a link to this issue in the PR I'm making.

**Comment by lwm** [comment]
Right, I didn't know groups were deprecated! Thanks for that.

I'll add tag logic to the inventory plugin when they land (hopefully a release comes soon!).

I'll go ahead and close this off since #140 addresses the need.

:+1:
