### ISSUE TITLE
request: client.linode.instance_delete

### ISSUE THREAD

**Issue by lwm** [linode/linode_api4-python#142]
I'll need to be able to delete instances and can't see that available right now.

**Comment by Dorthu** [comment]
You can delete instances (and any other deletable resource) with the `delete` method:

```python
instance = client.linode.instances().last()

instance.delete()
```

Note: This raises if the delete doesn't work (like if you try to delete something that can't be deleted like a Region object).

**Comment by lwm** [comment]
Solid, thanks!!!
