### ISSUE TITLE
Domain DNS can't create SRV record with protocols xmpp, tls, smtp

### ISSUE THREAD

**Issue by pjcunningham** [linode/linode_api4-python#171]
```
_domain_name = 'example.com'
client = LinodeClient(some_token)
_domains = _client.domains(Domain.domain == _domain_name)
_domain =  client.domains(Domain.domain == _domain_name).first() if _domains else None

if _domain:

    _service_data = {
        "name": "_sip._tls",
        "port": 443,
        "priority": 100,
        "protocol": "tls",
        "service": "sip",
        "tag": null,
        "target": "sipdir.online.lync.com",
        "ttl_sec": 3600,
        "weight": 1
    }

    try:
        _result = _domain.record_create('SRV', **_service_data)
    except Exeption as ex:
        print(ex)
```
Outputs:
`"400: Please select a valid protocol ('udp', 'tcp');"`

The cloud manager SRV record editor has the following protocols in the the `Protocol` dropdown list:

`tcp, udp, xmpp, tls, smtp`

![cloud linode-edit-service-record](https://user-images.githubusercontent.com/360727/72662998-7ddab280-39e5-11ea-86ca-6d6383ee124e.png)

**Comment by Dorthu** [comment]
I tried to create a SRV record through cloud.linode.com using a protocol of "tls" and got the same error as you are getting through this library.  This appears to be an upstream issue - I am opening an issue in our internal issue tracker.  You could also open a support ticket with this information if you like, although I'll try to keep this issue updated.

Just curious, can you save the above domain record in cloud?

**Comment by pjcunningham** [comment]
I can confirm that it doesn't work in cloud manager but creating/editing works in the old manager (which is about to be retired!). Regarding the screenshot, I'd forgotten that I'd actually created the record in the old manager.

**Comment by Dorthu** [comment]
I suspected as much.  This is being fixed upstream, and is expected to ship on Monday the 27th, which is ahead of the Classic Manager being retired.  I'll update this again when it's live.  Sorry for the inconvenience!

**Comment by Dorthu** [comment]
This should be fixed upstream now.  Please let me know if this is now working.

**Comment by pjcunningham** [comment]
Yes, this is now working.

Cheers, Paul.
