### ISSUE TITLE
Linode stats_for method is 404ing

### ISSUE THREAD

**Issue by lotooo** [linode/linode_api4-python#173]
The current `stats_for` method is currently 404ing cause the `format` part to call the client is broken.

https://github.com/linode/linode_api4-python/blob/master/linode_api4/objects/linode.py#L738

```
'{}/stats/'.format(dt.strftime('%Y/%m'))
```
return `2020/06/stats` which is not a valid endpoint.

 fixed it locally with 

```
'{}/stats/{}'.format(Instance.api_endpoint, today.strftime('%Y/%m'), model=self)
```

**Comment by Dorthu** [comment]
Thanks for the report - looks like an oversight, I'll get it fixed and a new build published today

**Comment by lotooo** [comment]
Thanks !

**Comment by Dorthu** [comment]
Just release 2.3.4 which includes this fix.  Thanks again for the detailed report!
