### ISSUE TITLE
accessing domain records causes: TypeError: 'PaginatedList' object is not callable

### ISSUE THREAD

**Issue by muradm** [linode/linode_api4-python#185]
According to documentation, seems like it should work like this:
```
client = ...
domain = client.domains(Domain.domain == domain)[0]
for record in domain.records():
    ...
```
However it throws `TypeError: 'PaginatedList' object is not callable`, but this works:
```
client = ...
domain = client.domains(Domain.domain == domain)[0]
for record in domain.records:
    ...
```
Note that, above is without call paranthesis.

**Comment by Dorthu** [comment]
What documentation are you looking at?  In the [Domains section](https://linode-api4.readthedocs.io/en/latest/linode_api4/objects/models.html#module-linode_api4.objects.domain) of the model documentation, `records` isn't listed as a callable, but if it is presented as such elsewhere that is certainly an error.

**Comment by muradm** [comment]
You seems to be right. Sorry, may be I mixed with some other object.
