### ISSUE TITLE
documentation: client.linode.instance_create stackscript_id parameter

### ISSUE THREAD

**Issue by sss0bbb** [linode/linode_api4-python#212]
While attempting some automation using StackScripts, I tried a few times to call client.linode.instance_create by passing an int to the stackscript parameter as specified in the documentation on readthedocs. Linode creation succeeded, but the StackScript seemed to fail. I checked the live website API call, which uses a different parameter named stackscript_id with an int value. Stackscript_id as a parameter for client.linode.instance_create works and is undocumented.

**Comment by Dorthu** [comment]
I believe this library should convert an integer given to `client.linode.instance_create` as `stackscript=123` to a `stackscript_id` in the request it generates: [link](https://github.com/linode/linode_api4-python/blob/e078c1b86f95e1f507a2b028d0098dc8d6c2fbb0/linode_api4/linode_client.py#L245-L249).

Do you have an example of the code you ran that produced this behavior?
