### ISSUE TITLE
Missing/Insufficent Documentation on how to query specific Linode instances

### ISSUE THREAD

**Issue by ejw9988** [linode/linode_api4-python#217]
I am trying to query the status of a Linode instance I created via the API. I haven't found any good examples of this being done anywhere online so I looked at the docs. Looking at the LinodeClient documentation, I see the client.linode.instances() function to get all instances: https://linode-api4.readthedocs.io/en/latest/linode_api4/linode_client.html?highlight=linode.instance_create#linode_api4.linode_client.LinodeGroup.instances

This function is supposed to take a filter as a parameter. However, when I try that exact example I get an error:
```
>>> client.linode.instances(Instance.group == "prod")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Instance' is not defined

```
Where is this 'Instance' object supposed to come from? I suspect there is an import I am missing, but the docs are only using: `from linode_api4 import LinodeClient`

It would be nice if there were more code example of doing common tasks with the API. I see some example of creating Linode instances but I can't find many for querying existing instances or changing configuration on existing instances.

**Comment by Dorthu** [comment]
Thanks for the feedback!  There is additional documentation on filtering [here](https://linode-api4.readthedocs.io/en/latest/guides/core_concepts.html#filtering), but it also does not include the full import paths required to actually make the example code work.  I'll update both example to include the relevant imports.

The docs note how to update existing models [here](https://linode-api4.readthedocs.io/en/latest/guides/core_concepts.html#updating-and-deleting-models); what could make this better to explain how to update existing services?
