### ISSUE TITLE
[Feature]: Add support for interfaces in `instance_create`

### ISSUE THREAD

**Issue by ericliuche** [linode/linode_api4-python#350]
### Description

Currently, it is not possible to attach interfaces upon [instance creation](https://github.com/linode/linode_api4-python/blob/dev/linode_api4/groups/linode.py#L132) even though it is possible with the public API

From https://www.linode.com/docs/api/linode-instances/#linode-create:
```
interfaces | array of objects

An array of Network Interfaces to add to this Linode’s Configuration Profile.
...
```

Adding support will allow me to attach vlans to my instances.

**Comment by ericliuche** [comment]
@lgarber-akamai thanks for the quick response! I just tried it out and it worked great. 

Unrelated to this, but is there a way to delete instances from the SDK?

**Comment by lgarber-akamai** [comment]
@ericliuche No problem at all!

>Unrelated to this, but is there a way to delete instances from the SDK?

You can delete an instance using the `Instance.delete()` method:

```python
instance_id = 12345
my_instance = Instance(client, instance_id)

my_instance.delete()
```

**Comment by ericliuche** [comment]
Ah thank you, I missed it since it was defined on the `Base` object and not `Instance`.
