### ISSUE TITLE
[Feature]: Add firewall to instance

### ISSUE THREAD

**Issue by guanzo** [linode/linode_api4-python#360]
https://www.linode.com/docs/release-notes/api/#api-v41673

> You can now assign a Firewall to a Linode compute instance by utilizing the firewall_id when running the [Linode Create](https://www.linode.com/docs/api/linode-instances/#linode-create) operation.

**Comment by zliang-akamai** [comment]
Hey @guanzo, thank you for the feature request! I think we already support creating Linodes under a Linode Cloud Firewall in the Python SDK.

```python
client=LinodeClient(token=os.getenv("LINODE_TOKEN"))


client.linode.instance_create(
    "g6-nanode-1",
    "us-mia",
    image="linode/debian12",
    firewall_id=12345,
)
```

You can replace the value of `firewall_id` with your firewall ID in this example to create a Nanode under the firewall. Does this code snippet work well for you? Please let us know if you have any question or issue.

**Comment by guanzo** [comment]
Sorry you're totally right. I grepped the source for `firewall_id` and didn't find anything so I assumed it wasn't supported.
