### ISSUE TITLE
No equivalent value for account transfer_pool

### ISSUE THREAD

**Issue by citaret** [linode/linode_api4-python#50]
I can not find how to get value for account transfer_pool from python api:
```
linode account show -j | grep transfer
      "transfer_pool" : 1393365,
      "transfer_used" : 348572,
      "transfer_billable" : 0,
```

```
In [14]: import linode
In [15]: client = linode.LinodeClient('SECRET')
In [16]: t = client.account.get_transfer()

In [17]: t.used, t.max, t.quota
Out[17]: (348572, 1388000, 1386111)
```

Here, `transfer_used` matches `t.used`, but `transfer_pool` can not match any value.

**Comment by Dorthu** [comment]
This library is showing the values returned from the API, which appear to be incorrect. I'll pass this along to our API development team to resolve the discrepancies.  Thanks for reporting, I'll leave this issue open for follow-up.

**Comment by Dorthu** [comment]
I believe that this issue is resolved - please verify and close this issue.  The "transfer_pool" value returned by the api v3 should now be returned as "quota".
