### ISSUE TITLE
Get images

### ISSUE THREAD

**Issue by abusquets** [linode/linode_api4-python#69]
When I try to get images I have always an error.

I tested with curl
curl -H "Authorization: token $token" https://api.linode.com/v4/images
{"errors": [{"reason": "Internal server error"}]}

and with python

client = LinodeClient(t)
result = client.get('/images')

**Comment by jamesottinger** [comment]
I'm seeing an error on our end for those calls. We will investigate further and give you an update once it is resolved. Thank you for reporting.

**Comment by Dorthu** [comment]
We have a fix for this staged, it will be released on Monday. I will update this ticket once it is released

**Comment by lgarber-akamai** [comment]
Closing since this issue appears to be resolved. Feel free to @ me if this issue is still relevant.
