### ISSUE TITLE
Saving DomainRecord

### ISSUE THREAD

**Issue by adontz** [linode/linode_api4-python#76]
When I programmatically read A record created from UI, change target try to save I receive the following errors

{'field': 'protocol', 'reason': 'Invalid value'}
{'field': 'service', 'reason': 'Invalid value'}

Values of both fields were read as None and were not modified. I expect call to succeed.

**Comment by Dorthu** [comment]
This also look to be a bug on our side.  I've added this to our internal bug tracker and will update this when it's been resolved.

**Comment by adontz** [comment]
For now I calculate difference between existing and desired and create/ignore/delete. It works, but is it optimal? I don't know how your system works, so while I have a workaround this bug should probably be fixed still.

**Comment by Dorthu** [comment]
This issue has been fixed on our end.  If you could, please confirm it is working as expected and close this issue.  Thanks!

**Comment by lgarber-akamai** [comment]
I tested this locally and it appears to be resolved.
