### ISSUE TITLE
OpenAPI 2 spec for Linode api v4

### ISSUE THREAD

**Issue by tamalsaha** [linode/linode_api4-python#79]
We would like to access Linode v4 api using GO for our [Kubernetes installer](https://github.com/appscode/pharmer). It will be much easier to maintain clients in other langues  if Linode could provide OpenAPI 2 (previously called swagger 2.0) spec. Then we could auto generate GO client using tools like https://github.com/go-swagger/go-swagger . Clients in many languages can be generated using such spec. https://github.com/swagger-api/swagger-codegen

OpenAPI is becoming the standard language for documenting api specs. Here are some other examples:
- https://medium.com/box-developer-blog/embracing-openapi-swagger-at-box-3e9239a57db6
- https://medium.com/slack-developer-blog/standard-practice-slack-web-openapi-spec-daaad18c7f8

I read from your blog that you use Flask for backend. May be tools like below can help create the specs:
- https://github.com/remcohaszing/flask-openapi
- https://github.com/zalando/connexion

**Comment by Dorthu** [comment]
We have been looking into this, and there is a good chance of us supporting it in the future.  Presently, the API V4 is still in beta, and this is likely something that would be done around the end of the beta period or soon after 1.0.  You can keep an eye on our [changelogs](https://developers.linode.com/v4/changelogs) to see when an OpenAPI spec is available (I'll try to remember to update this issue when it comes out, too).

**Comment by Dorthu** [comment]
Just an update: The OpenAPI spec should be released within the next two weeks - we ended up on OpenAPI 3.0.  It will be available at https://developers.linode.com when it goes online.  I'll do my best to update this again when that happens.  Thanks for your patience!
